equinor/fusion-web-components

package.json
packages/popover/.eslintrc
packages/popover/package.json
packages/popover/src/directories/popperjs.ts
packages/popover/src/element.css.ts
packages/popover/src/element.ts
packages/popover/src/index.ts
packages/popover/tsconfig.json
storybook/package.json
storybook/stories/popover.stories.mdx
storybook/tsconfig.json
tsconfig.json

- create component
- create dictionary for PopperJS
- create story for popover

feat(popover): create element for popover

---

packages/textinput/src/index.ts

fix: added export for styles

---

packages/textarea/.eslintrc
packages/textarea/CHANGELOG.md
packages/textarea/README.md
packages/textarea/package.json
packages/textarea/src/element.css.ts
packages/textarea/src/element.ts
packages/textarea/src/index.ts
packages/textarea/tsconfig.json
storybook/package.json
storybook/stories/checkbox.stories.mdx
storybook/stories/radio.stories.mdx
storybook/stories/switch.stories.mdx
storybook/stories/textarea.stories.mdx
storybook/stories/textinput.stories.mdx
storybook/tsconfig.json
tsconfig.json

feat: added textarea component

---

packages/button/src/element.ts
packages/button/src/index.ts

- Added global type definition for JSX element.
- Added missing properties in props type definition.

fix: fixed typedef

---

packages/button/README.md
packages/button/package.json
packages/button/src/element.ts

* Fixed readme file typos
* Added missing extension for HTMLElement to props type definition

fix: fixed readme and type definition

---

packages/badge/package.json

fix: fixed publish config

---

packages/checkbox/src/element.css.ts
packages/checkbox/src/element.ts
packages/checkbox/src/index.ts
storybook/stories/checkbox.stories.mdx

+ add css attrbiute for size
+ add css attribute for padding
+ update storybook

feat(checkbox): allow sizing of checkbox

---

packages/list/src/list-item/element.css.ts

Added overflow hidden to list element to allow adding ellipsis to long text on the list element.

fix(List): Add overflow hidden to list element

---

packages/button/src/element.css.ts

Fixing colors for all of the button types.

fix(Button): replace old variables in button element css

---

package-lock.json
package.json
packages/progress-indicator/src/star/graphics.svg.ts

fix(star): use correct css variable for svg size

---

packages/person/README.md
packages/person/package.json
packages/person/src/index.ts
packages/person/src/person-avatar/element.ts
packages/person/src/person-card/element.css.ts
packages/person/src/person-card/element.ts
packages/person/src/person-card/index.ts
packages/person/src/person-card/types.ts
packages/person/src/types.ts
storybook/stories/Components/PersonCard.tsx
storybook/stories/person-avatar.stories.mdx
storybook/stories/person-card.stories.mdx

Created web component "Person Card" based on fusion component "PersonDetails"
The person card component provides the option to render a persons avatar, availability, and all additional information from a PersonResolver interface like name, email, phone, job title, department, location.

Feat/person card/create person card

---

package-lock.json
packages/searchable-dropdown/package.json
packages/searchable-dropdown/src/dropdown/element.ts
packages/searchable-dropdown/tsconfig.json

Expose used web components to component scope.

Fix/searchable dropdown/expose/tags

---

.github/workflows/generate-docs.yml

Fixing the generate-docs workflow with proper commit message.
Future: possibly disable husky in ci enviorment

ci(workflow): fixes conventional commit message in generate-docs action

---

packages/searchable-dropdown/src/provider/controller.ts
storybook/stories/Components/SearchableDropdown.tsx

Fixing a bug where the selected item was not highlighted when not using sectioned result lists.

fix(searchabledropdown): show selected item on sectioned and flat list

---

packages/searchable-dropdown/src/types.ts

Improving typehinting on the select event

fix(searchabledropdown): typehinting for select event

---

packages/searchable-dropdown/package.json

Just a manual version bump since version tag already existed.

fix(searchabledropdown): manual version bump

---

packages/person/src/index.ts
packages/person/src/person-provider/element.ts

fix(person): resolver fix

---

packages/button/package.json
storybook/stories/Components/Button.tsx

fix(button): adding changelog to exports

---

packages/icon/package.json
storybook/stories/icon.stories.mdx

[Web components: Update and test dependencies ](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/35994)
Update equinor/eds-icons form 0.15.0 to 0.18.0 and make few changes in storybook available icon list

chore: :package: update icon

---

package-lock.json
package.json
packages/avatar/package.json
packages/badge/package.json
packages/button/package.json
packages/checkbox/package.json
packages/chip/package.json
packages/date/package.json
packages/divider/package.json
packages/formfield/package.json
packages/icon/package.json
packages/intersection/package.json
packages/list/package.json
packages/menu/package.json
packages/person/package.json
packages/picture/package.json
packages/popover/package.json
packages/progress-indicator/package.json
packages/radio/package.json
packages/ripple/package.json
packages/searchable-dropdown/package.json
packages/select/package.json
packages/skeleton/package.json
packages/switch/package.json
packages/textarea/package.json
packages/textinput/package.json
packages/theme/package.json
storybook/.storybook/custom_element.js
storybook/.storybook/preview.js

[Web components: Update and test dependencies ](https://dev.azure.com/statoil-proview/Fusion/_workitems/edit/35994)
Update component dependencies and "already defined" error in storybook fix

Chore/web components/dependencies

---

packages/person/src/person-card/element.ts
packages/person/src/person-provider/controller.ts
packages/person/src/types.ts

[PersonProvider: handle controller when Promise not resolved](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/35983)
close #465 
Handle controller when Promise not resolved

fix: :stethoscope: handle error

---

packages/button/src/icon-button/element.ts
storybook/stories/icon-button.stories.mdx

href and target atributes used for linking the icon button

feat: :sparkles: link icon button

---

packages/markdown/CHANGELOG.md
packages/markdown/README.md
packages/markdown/package.json
packages/markdown/src/index.ts
packages/markdown/src/markdown-editor/element.css.ts
packages/markdown/src/markdown-editor/element.ts
packages/markdown/src/markdown-editor/index.ts
packages/markdown/src/markdown-editor/keymap.ts
packages/markdown/src/markdown-editor/menu.ts
packages/markdown/src/markdown-editor/menuItems.ts
packages/markdown/src/markdown-editor/types.ts
packages/markdown/src/types.ts
packages/markdown/tsconfig.json
storybook/package.json
storybook/stories/Components/MarkdownEditor.tsx
storybook/stories/markdown-editor.stories.mdx
storybook/tsconfig.json
tsconfig.json

[Component - Markdown Editor - Azure DevOps](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/36995)
Web component used for editing markdown content. Moved and changed from React components to Web components repository

feat(markdown-editor): created component

---

packages/markdown/package.json
packages/markdown/src/index.ts
packages/markdown/src/markdown-viewer/element.ts
packages/markdown/src/markdown-viewer/index.ts
packages/markdown/src/markdown-viewer/types.ts
storybook/stories/Components/MarkdownViewer.tsx
storybook/stories/markdown-viewer.stories.mdx
storybook/stories/resources/markdown.example.ts

feat(markdown): add markdown-viewer

---

packages/person/src/person-card/element.css.ts
storybook/stories/person-card.stories.mdx

- Default (white) person card background
- Minimum width for person card
close: #652

fix(person-card): card background and minimum width

---

packages/button/src/icon-button-toggle/element.ts
packages/button/src/icon-button/element.ts
packages/button/src/icon-button/types.ts

[[Icon Button] Web component - Icon button color and size type export](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/42194)

Fix/icon button/types

---

packages/person/src/person-avatar/element.css.ts
packages/person/src/person-avatar/element.ts
packages/person/src/person/element.ts
packages/person/src/style.css.ts
packages/person/src/types.ts
storybook/stories/Components/PersonCard.tsx

- Change avatar background color on different account type.
- Add typing for manager azure id in person details
[[Person Card] Background color for avatar](https://statoil-proview.visualstudio.com/Fusion/_workitems/edit/42021)

fix(person): account type background

---

packages/person/src/person-card/element.ts
packages/person/src/person-card/event.ts
packages/person/src/person-card/task.ts
packages/person/src/person-card/types.ts
packages/person/src/person-provider/element.ts
packages/person/src/person-provider/types.ts
storybook/stories/Components/PersonAvatar.tsx
storybook/stories/Components/PersonCard.tsx
storybook/stories/person-card.stories.mdx

BREAKING: Person card can now be resolved in 3 different ways:
- By setting the `azureId` prop on the element - will resolve in resolver.
- By setting the `upn` prop on the element - will resolve in resolver.
- By setting the `dataSource` - will immediately resolve in the task.

feat!(person): update card to resolve from task

---

packages/person/src/components/avatar/element.ts

fix(person-avatar): fix avatar size on task error

---

packages/person/src/components/avatar/element.ts

fix(person-avatar): pass upn as well as azureId to the person card

---

packages/person/src/events.ts
packages/person/src/tasks/person-detail-task.ts
packages/person/src/tasks/person-info-task.ts
packages/person/src/tasks/person-photo-task.ts
packages/person/src/tasks/person-search-task.ts
packages/person/src/types.ts

see https://github.com/equinor/fusion-framework/issues/1259

feat(person): add abort signal to request events

---

.changeset/chilly-ligers-clap.md
packages/person/package.json

swap places with default and types in package export

fix(person): swap export places in package

---

.changeset/popular-books-repeat.md
packages/person/src/components/avatar/element.css.ts
packages/person/src/components/avatar/element.ts

fix(person/avatar): fix calculation of floating ui

---

.changeset/big-trees-film.md
packages/searchable-dropdown/src/dropdown/element.ts
storybook/stories/Components/SearchableDropdown.tsx

feat(searchable-dropdown): add meta slot

---

.github/workflows/actions/node-setup/action.yml
package.json

- add suppered engines and packageManager to package.json
- removed package version form workflow

chore(web-components): engines and packageManager

---

.changeset/happy-goats-perform.md
packages/person/package.json
packages/person/src/components/avatar/element.ts
packages/person/src/components/avatar/types.ts
packages/person/src/components/card/element.ts
packages/person/src/components/list-item/element.ts
packages/person/src/components/select/element.ts
pnpm-lock.yaml

- update imports
- fixed missing imports
- fixed typing

fix(person): broken import paths

---

.changeset/ten-pumpkins-beg.md
packages/searchable-dropdown/src/dropdown/element.ts

fix(searchable-dropdown): add `part` attribute to list and list-items

---

package.json

Fixing the mono-repo start script command for starting storybook.

fix(package): fixing start script command

---

.changeset/tame-panthers-switch.md
packages/searchable-dropdown/src/provider/controller.ts

Searchable-dropdown list now select first available search result on keypress *Enter* while searching.

feat(searchabledropdown): select first searchresult on keypress enter

---

.changeset/healthy-peaches-lay.md
packages/searchable-dropdown/src/provider/controller.ts

Removing console.log in searchable-dropdown controller.

chore(searchable-dropdown): removing console.log in controller

---

.changeset/wicked-guests-bow.md
packages/person/src/components/avatar/element.css.ts
packages/person/src/components/avatar/element.ts

fix(person-avatar): account color

---

.changeset/chatty-trees-think.md
packages/searchable-dropdown/src/dropdown/element.ts
packages/searchable-dropdown/src/types.ts
storybook/stories/input/searchable-dropdown.stories.ts

Ref [AB#44766](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/44766)

feat(searchable-dropdown): add attr/prop select-text-on-focus

---

.changeset/new-humans-fly.md
packages/list/package.json
packages/list/src/index.ts

fix(list): exporting sub-components from fwc-list

---

.changeset/forty-cows-sparkle.md
packages/person/src/components/avatar/element.ts
storybook/stories/person/person-avatar.stories.ts

feat(person): prevent card when avatar is disabled

---

.changeset/grumpy-monkeys-glow.md
packages/person/src/components/select/controller.ts
packages/person/src/components/select/element.ts

This fixes the issue in CLI where the components update cycle is quicker then the resolver.
Please give feedback if any other solutions is possible.

fix(person-select): fixes awaiting resolver in cli

---

.changeset/eleven-scissors-help.md
packages/searchable-dropdown/src/dropdown/element.css.ts
storybook/stories/input/searchable-dropdown-provider.ts

- Opacity and color to disabled and error list item

fix(searchable-dropdown): disabled/error color

---

.changeset/big-kids-shout.md
packages/person/src/components/select/controller.ts
packages/person/src/components/select/element.ts

Fixes conflicts when you have 2 different tasks running.
Reference [AB#49807](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/49807)

fix(person-select): fixes task conflicts and refactoring

---

.changeset/large-hornets-tickle.md
storybook/stories/person/person-select.stories.ts

Corrects ending tag for fwc-person-select in storybook

fix wrong ending tag for personselect story

---

.changeset/beige-zoos-learn.md
packages/person/src/components/avatar/element.ts

[AB#48502](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/48502)
- Added stopPropagation to person card to prevent triggering click from parent

fix(person-avatar): person card click

---

.github/dependabot.yml

not only minor and patch
Ref #1489

chore(dependabot): group all storybook updates

---

.changeset/twelve-moles-grab.md
packages/person/src/components/avatar/element.ts

fix(person-avatar): fix inconsistent hover behavior when posisition is bottom

---

.changeset/brown-mangos-attend.md
packages/person/src/components/table-cell/element.ts

small fix: Change "undefined" look of the cell

fix(table-cell): undefined cell

---

.changeset/big-grapes-matter.md
packages/searchable-dropdown/src/dropdown/element.css.ts
packages/searchable-dropdown/src/dropdown/element.ts

fix(searchable-dropdown): re-add styling + fix arrow down

---

.changeset/long-dolls-fold.md
packages/person/src/components/select/element.css.ts

fix(person): re-add styling for person select

---

.changeset/big-seals-tell.md
package.json
packages/person/package.json

Enhance TypeScript compatibility by updating package exports and adding type definitions. Adjust the Node engine version in package.json to support newer versions.

Update package exports for TypeScript compatibility

---

.changeset/add-clear-formatting.md
.changeset/update-storybook-tx-button.md
packages/markdown/package.json
packages/markdown/src/markdown-editor/extentions/clear-formatting.ts
packages/markdown/src/markdown-editor/menu.ts
packages/markdown/src/markdown-editor/menuItems.ts
packages/markdown/src/markdown-editor/utils/prosemirror-utils.ts
pnpm-lock.yaml
storybook/package.json
storybook/stories/input/markdown-editor.stories.ts

Ref [AB#64464](https://statoil-proview.visualstudio.com/3dadd756-da44-4bb3-8874-330932214dff/_workitems/edit/64464)
Ref equinor/fusion#507

feat(markdown-editor): add "Clear Formatting" functionality

---

.changeset/moody-crews-nail.md
packages/person/src/components/card/element.css.ts

PersonCard text-break long names

fix: enhance text handling in PersonCard for long names
